### ISSUE TITLE
yarn run build-main error

### ISSUE THREAD

**Issue by mmelvin0581** [nuclearide/nuclear#2]
Michaels-iMac:nuclear mmelv$ yarn run build-main
yarn run v1.6.0
(node:47818) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ parcel watch index.js --target electron
/bin/sh: parcel: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mmelvin0581** [comment]
I believe it's because I am using yarn 1.6. I ran with npm and it built and opened just fine. Nothing seem to be working inside the app though. Is this thing usable yet?

**Comment by simonhochrein** [comment]
Nuclear is in active development, most things don’t work, but help is appreciated 😃 

Interesting error, don’t quite know what could cause that.

**Comment by reetou** [comment]
@mmelvin0581 Did you try it with yarn v1.3.2?

**Comment by mmelvin0581** [comment]
I don’t remover buddy sorry

**Comment by reetou** [comment]
Closing then.
